### ISSUE TITLE
JavaScript - Variable declaration

### ISSUE THREAD

**Issue by raciat** [vgno/coding-standards#39]
Could you update `Variable declaration` section in https://github.com/vgno/coding-standards/tree/master/javascript#variable-declaration? 

First of all you read `as close as possible to the place where it's first used.`, `on a new line` and then `var object = {}, key;`. Doesn't make any sense, does it?

To make it faster you can copy recently updated text from: https://github.com/yandex/codestyle/blob/master/javascript.md#variable-declaration ;)

I wanted to send a PR but somehow I don't have permission.

**Comment by rexxars** [comment]
This is a public Github repo, anyone with an account should be able to send PRs.
