### ISSUE TITLE
JavaScript: Allow use of the const keyword

### ISSUE THREAD

**Issue by androa** [vgno/coding-standards#41]
We have https://github.com/vgno/coding-standards/blob/master/javascript/README.md#const-keyword in place now.

Should we not allow the const keyword?

IMHO we should allow more ES6 features now on a general basis. Maybe a separate issue?

**Comment by dlmr** [comment]
I would even go as far to suggest adding this to the standard: http://eslint.org/docs/rules/prefer-const.html

**Comment by raciat** [comment]
IMO we definitely should. I would also recommend to follow "use `const` by default and only use `let` when you know a variable’s value needs to change" rule.

**Comment by mdrobny** [comment]
I think we would need separate coding standards for ES6 features, mixing it with the old one would be confusing. Like this one: https://github.com/airbnb/javascript - ES6 is the main one, ES5 is in "others"
